### PR TITLE
Pass the name of droplet as argument while destroying droplet

### PR DESCRIPTION
**Pull request by goldobin**

### CODE REVIEW

**Comment by gsnewmark** [comment]
Why make it argument instead of option? Moreover, I think prefix and name options are overlapping - not sure we need both of them.

Help text for id and prefix options should be updated.

**Comment by goldobin** [comment]
For me it is more convenient. I have caught myself today like typing `dop.py droplet destroy node01` today.

And yes they are overlapping. Actually there is **OR** logic which allows you to destroy droplets with different prefixes, labels and names at once.

**Comment by gsnewmark** [comment]
But you can supply whole name as a prefix, and it will work exactly like passing it as name arg/option. Why not pass prefix as argument (and remove name completely)?  So that it's possible to execute both `dop.py droplet destroy node01` to delete specific node and `dop.py droplet destroy node` to delete all nodes.

The only problem is when we have a node with name that is also a prefix of another node, for example `node`, `node1`, `node2`. If we intend to support such scenarios then separate prefix/name options should be left.

**Comment by gsnewmark** [comment]
Will you update help messages in this PR or a separate issue/PR should be created?

**Pull request merged**
